### ISSUE TITLE
Choosing the logo for JuliaStochOpt org. 

### ISSUE THREAD

**Issue by frapac** [JuliaStochOpt/StochOptInterface.jl#3]
Two choices: 

- [with arrows](http://cermics.enpc.fr/~pacaudf/stochopt.svg) (:heart:)
- [without arrows](http://cermics.enpc.fr/~pacaudf/stochopt2.svg) (:+1:)

**Comment by frapac** [comment]
Personally, I am more in favor of the first logo (with arrows), just to mark a difference with the logo of JuliaOpt (which was undoubtedly a great source of inspiration)

**Comment by leclere** [comment]
Excellent :-) Maybe a tad complicated and really oriented toward polyhedral approximations.

**Comment by trigaut** [comment]
👍

**Comment by trigaut** [comment]
No sorry ❤️haha
